Variables in crew/chat apps
rnadigital/agentcloud pull request #490
Opened 2024-08-27 06:25 UTC by charl3sj

2024-08-27 06:26 UTC, charl3sj commented
WIP. Frontend bits pending.

2024-09-18 01:58 UTC, tomlynchRNA requested changes
Two issues:
- ChatAppForm doesn't support the variables (it doesn't use AgentForm component)
- Cloning an agent no longer prepopulates the role/goal/backstory with ones from the cloning agent

2024-09-20 00:53 UTC, tomlynchRNA approved these changes

2024-09-20 00:55 UTC, tomlynchRNA requested changes
Changes required:
- Allow a variable to be used multiple times in 1 input
- Initialize usedInTasks/usedInAgents to empty array when creating variables
- If you open a task, type a { and create a variable, but then in another tab delete it, it still gets submitted in variableIds when you save the task, but the variable no longer exists

2024-09-25 04:05 UTC, merged