Remove `recursion_limit` config option but limit length of messages
rnadigital/agentcloud pull request #521
Opened 2024-09-05 15:41 UTC by charl3sj

Ref https://github.com/rnadigital/agentcloud/issues/520

2024-09-11 05:22 UTC, tomlynchRNA commented on webapp/src/migrations/1.9.0.ts
> +				'chatAppConfig.recursionLimit': 'chatAppConfig.maxMessages'
@charl3sj can you update package.json version to 1.9.0 to correspond with this? Good job on already making the migration :smile:

2024-09-11 23:44 UTC, tomlynchRNA commented
@charl3sj  Here are two runs with max messages set to 5:

![image](https://github.com/user-attachments/assets/63da5601-fba2-46c2-ac1b-8a00baefef78)
(more than 5 messages)


![image](https://github.com/user-attachments/assets/475a0aca-04e2-43aa-b2a9-4a21e9cc0fea)
(less than 5 messages)

I added some logs and in the first example, if you then ask a question that uses a tool and streams, it does stop the chat, and my `len(past_messages)` was 26. So in the first example, I think it's missing a check for max_messages somewhere.

In the second run, I think it's counting some messages that are not sent to the frontend?

2024-09-11 23:45 UTC, tomlynchRNA requested changes
See comment :point_up:

2024-09-12 11:16 UTC, charl3sj commented
> In the second run, I think it's counting some messages that are not sent to the frontend?

Yep, there are more messages in state than are shown in the frontend. I moved the limit checking logic to a function [here](https://github.com/rnadigital/agentcloud/pull/521/commits/5eb0dd9e6633b3f6b8179cefec1c19df5f335424#diff-3a034cc0b56e9a5b1dcb7fee42141f947bb1e9cbefc084c3b4dcd9b98c212bddR86) that we can tweak. Also, moving the check to [here](https://github.com/rnadigital/agentcloud/pull/521/commits/5eb0dd9e6633b3f6b8179cefec1c19df5f335424#diff-3a034cc0b56e9a5b1dcb7fee42141f947bb1e9cbefc084c3b4dcd9b98c212bddR152) can yield more precise behavior. Leaving it where it is [now](https://github.com/rnadigital/agentcloud/pull/521/commits/5eb0dd9e6633b3f6b8179cefec1c19df5f335424#diff-3a034cc0b56e9a5b1dcb7fee42141f947bb1e9cbefc084c3b4dcd9b98c212bddR101) allows for some latitude in the limit check in that it waits for one loop iteration to end so that it doesn't stop in the middle of a response.

2024-09-12 22:35 UTC, tomlynchRNA approved these changes

2024-09-12 22:35 UTC, merged